// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test/test.proto

package test

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Person struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32    `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Children             []int32  `protobuf:"varint,3,rep,packed,name=children,proto3" json:"children,omitempty"`
	Note                 string   `protobuf:"bytes,128,opt,name=note,proto3" json:"note,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_test_dcae93729d660b16, []int{0}
}
func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (dst *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(dst, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Person) GetChildren() []int32 {
	if m != nil {
		return m.Children
	}
	return nil
}

func (m *Person) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func init() {
	proto.RegisterType((*Person)(nil), "test.Person")
}

func init() { proto.RegisterFile("test/test.proto", fileDescriptor_test_dcae93729d660b16) }

var fileDescriptor_test_dcae93729d660b16 = []byte{
	// 126 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x49, 0x2d, 0x2e,
	0xd1, 0x07, 0x11, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x2c, 0x20, 0xb6, 0x52, 0x3c, 0x17,
	0x5b, 0x40, 0x6a, 0x51, 0x71, 0x7e, 0x9e, 0x90, 0x10, 0x17, 0x4b, 0x5e, 0x62, 0x6e, 0xaa, 0x04,
	0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x98, 0x2d, 0x24, 0xc0, 0xc5, 0x9c, 0x98, 0x9e, 0x2a, 0xc1,
	0xa4, 0xc0, 0xa8, 0xc1, 0x1a, 0x04, 0x62, 0x0a, 0x49, 0x71, 0x71, 0x24, 0x67, 0x64, 0xe6, 0xa4,
	0x14, 0xa5, 0xe6, 0x49, 0x30, 0x2b, 0x30, 0x6b, 0xb0, 0x06, 0xc1, 0xf9, 0x42, 0xc2, 0x5c, 0x2c,
	0x79, 0xf9, 0x25, 0xa9, 0x12, 0x0d, 0x30, 0x23, 0xf2, 0x4b, 0x52, 0x93, 0xd8, 0xc0, 0xb6, 0x19,
	0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xcc, 0xfe, 0x2e, 0xf5, 0x80, 0x00, 0x00, 0x00,
}
